- name: configuring roboshop databases using below list
  hosts: 
  become: true
  tasks:
    - name: "installing {{ item }} server"
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
    - name: "start {{ item }} server"
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
    - name: "enable {{ item }} server"
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
      loop:
      - mongodb-org